### ISSUE TITLE
Modifying the code to adapt to my own HA sensors

### ISSUE THREAD

**Issue by facero** [Love4yzp/sensecap-indicator-ha#5]
Hi,

I'm able to compile the project and have the device show what the demo. MQTT works and I can interact with the switch on the device and see them on my HA.

Now the next step is that I want to remove the demo sensors/switch and add my own sensors from my HA installation.

From the HA side I'm able to create a dashboard with the sensors I want to show.
From the sensecap side, which file should be modified and where do I indicate the name of my HA sensor ? 

I first tried to play with the `home_assistant_config.h` file and removing the unwanted sensors/switch without success.

My use case is simple, I just want to display 3 values from sensors without anything fancy.

Thanks a lot for the cool project, I'm now very close to get it working with my HA !

**Comment by Love4yzp** [comment]
Hi, for sensecap indicator side.
You'll need to see the prefix name: 'indicator_sensorxxx'.
actually home_assistant_config is used for mqtt communication to HA.

**Comment by facero** [comment]
Thanks for the feedback !

Do you mean the lines in this function ? By adding/removing some sensors there ?
https://github.com/Love4yzp/sensecap-indicator-ha/blob/34567d3ca21f44928d05f4e377320938e50ec24f/main/app/indicator_sensor_view.c#L88

Then where should I indicate the HA name of my sensor ? I this variable `CONFIG_SENSOR1_VALUE_KEY`
https://github.com/Love4yzp/sensecap-indicator-ha/blob/34567d3ca21f44928d05f4e377320938e50ec24f/main/home_assistant_config.h#L46

**Comment by Love4yzp** [comment]
The way these code files are organized clearly demonstrates the MVC (Model-View-Controller) design pattern. You can consider LVGL (Light and Versatile Graphics Library) as acting as the Controller in this setup.

The function located in 

https://github.com/Love4yzp/sensecap-indicator-ha/blob/34567d3ca21f44928d05f4e377320938e50ec24f/main/app/indicator_sensor_model.c#L158-L192

which is responsible for automatically updating sensor data. You'll need to modify this function to handle the data for your corresponding sensor. This file and its functions represent the Model component, managing the application's data and business logic.

If you want to display this sensor data on your indicator panel, you'll need to modify the file: `indicator_sensor_view.c`. This file represents the View component, responsible for presenting the data to the user.

**Comment by hyacin75** [comment]
> The way these code files are organized clearly demonstrates the MVC (Model-View-Controller) design pattern.

Sorry but NOTHING about this is "clear" or "clearly demonstrates" anything, and nothing on the project page indicates you'll need a CS degree and C++ experience or whatever to make this thing work.

I'm not sure you guys are very clear about who you're targeting when you sell things that claim HA support/integration.  From what I've seen we're mostly hobbyists and hackers who can muddle our way through getting things working, but do NOT bring CS-degree level knowledge to the table more often than not.

@facero did you have any luck with this?  I'm in the exact same boat - I purchased this device simply to display and interact with some existing items in HA (a thermostat and a couple simple buttons) and it's REALLY looking like I bought the wrong thing for the job (yet again I'm afraid, when it comes to Seeed products.)

**Comment by melgu** [comment]
@hyacin75 @facero Its probably easier to start with ESPHome. There's an [overview page for the Seeed Indicator](https://devices.esphome.io/devices/seeed-sensecap/). ESPHome has an [LVGL component](https://esphome.io/components/lvgl/), which is the graphics library used in this repo.

I don't have any experience addressing touchscreens in ESPHome yet, but some experience with ESPHome in general, so it's a way I'll try.

**Comment by melgu** [comment]
Quick update: ESPHome is indeed the way to go. I've got a basic UI set up, can transmit the button to Home Assistant and can control the display from Home Assistant. I'm currently still struggling with the sensors. The [code provided](https://devices.esphome.io/devices/seeed-sensecap/#using-co2-and-tvoc-sensors-d1s-d1pro-only) on the ESPHome page for the Indicator doesn't seem to work out of the box.

**Comment by melgu** [comment]
Another update: The code provided for the sensors does work. Just make sure that the device name for the sensor provider in your main (ESP32) YAML matches the device name of the BT2040 YAML.

Here is my current configuration to get you startet:

<details>
<summary>sensecap-indicator-1.yaml</summary>

```yaml
esphome:
  name: sensecap-indicator-1
  friendly_name: SenseCAP Indicator 1

# Device-specific Basics

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

logger:
  hardware_uart: UART0
  level: DEBUG

output:
  - platform: ledc
    pin:
      number: GPIO45
      ignore_strapping_warning: true
    id: ledc_gpio45
    frequency: 100Hz

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO38
      inverted: true
    name: "User Button"

i2c:
  - id: bus_a
    sda: GPIO39
    scl: GPIO40
    scan: false

spi:
  - id: lcd_spi
    clk_pin: GPIO41
    mosi_pin: GPIO48
    miso_pin: GPIO47

pca9554:
  - id: pca9554a_device
    address: 0x20
    pin_count: 16

# Wi-Fi, OTA & Home Assistant

api:
  encryption:
    key: "XXXXX Add your own key here XXXXX"

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  enable_btm: true
  enable_rrm: true

# Sensors from RP2040

uart:
  - id: rp2040_serial
    tx_pin: GPIO20
    rx_pin: GPIO19
    baud_rate: 115200

packet_transport:
  - platform: uart
    uart_id: rp2040_serial
    providers:
      - name: sensecap-indicator-1-rp2040

sensor:
  - platform: packet_transport
    provider: sensecap-indicator-1-rp2040
    id: voc
    name: VOC Index
    internal: False
    accuracy_decimals: 0
    icon: "mdi:weather-dust"
    device_class: aqi
  - platform: packet_transport
    provider: sensecap-indicator-1-rp2040
    id: co2
    name: CO2
    internal: False
    accuracy_decimals: 0
    icon: "mdi:molecule-co2"
    unit_of_measurement: "ppm"
    device_class: volatile_organic_compounds_parts
  - platform: packet_transport
    provider: sensecap-indicator-1-rp2040
    id: temp
    name: Temperature
    internal: False
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    unit_of_measurement: "°C"
    device_class: temperature
  - platform: packet_transport
    provider: sensecap-indicator-1-rp2040
    id: humid
    name: Humidity
    internal: False
    accuracy_decimals: 1
    icon: "mdi:water-percent"
    unit_of_measurement: "%"
    device_class: humidity

# Display

display:
  - platform: mipi_rgb
    model: SEEED-INDICATOR-D1
    id: sensecap_display

light:
  - platform: monochromatic
    name: "Backlight"
    id: backlight
    output: ledc_gpio45
    restore_mode: ALWAYS_ON
    on_turn_on:
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
    on_turn_off:
      - if:
          condition:
            - not: lvgl.is_paused
          then:
            - lvgl.pause:

touchscreen:
  platform: ft5x06
  id: sensecap_touchscreen
  transform:
    mirror_x: true
    mirror_y: true
  on_release:
    - if:
        condition: lvgl.is_paused
        then:
          - lvgl.resume:
          - lvgl.widget.redraw:
          - light.turn_on: backlight

image:
  - file: https://esphome.io/favicon-512x512.png
    id: boot_logo
    resize: 200x200
    type: RGB565
    transparency: alpha_channel

lvgl:
  on_idle:
    timeout: !lambda "return 10000;"
    then:
      - light.turn_off: backlight
      - lvgl.pause:

  top_layer:
    widgets:
      - obj:
          id: boot_screen
          x: 0
          y: 0
          width: 100%
          height: 100%
          bg_color: 0xffffff
          bg_opa: COVER
          radius: 0
          pad_all: 0
          border_width: 0
          widgets:
            - image:
                align: CENTER
                src: boot_logo
                y: -40
            - spinner:
                align: CENTER
                y: 95
                height: 50
                width: 50
                spin_time: 1s
                arc_length: 60deg
                arc_width: 8
                indicator:
                  arc_color: 0x18bcf2
                  arc_width: 8
```

</details>

<details>
<summary>sensecap-indicator-1-rp2040.yaml</summary>

```yaml
esphome:
  name: sensecap-indicator-1-rp2040
  friendly_name: SenseCAP Indicator 1 RP2040

rp2040:
  board: rpipico

# Enable logging
logger:

uart:
  - id: esp32s3_serial
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 115200

i2c:
  - sda: GPIO20
    scl: GPIO21

sensor:
  - platform: sgp4x
    voc:
      id: voc
      name: "VOC Index"
  - platform: scd4x
    co2:
      id: co2
      name: "CO2"
    temperature:
      id: temp
      name: "Temperature"
    humidity:
      id: humid
      name: "Humidity"

power_supply:
  - id: 'sensor_supply1'
    pin: GPIO18
    enable_on_boot: True

packet_transport:
  - platform: uart
    uart_id: esp32s3_serial
    sensors: 
      - id: voc
      - id: co2
      - id: temp
      - id: humid
```

</details>
